### GET TODOS
GET http://localhost:8000/api/todos

### SINGLE TODO
GET http://127.0.0.1:8000/api/todos/2

### BAD POST request
POST http://localhost:8000/api/todos/
Content-Type: application/json

{
    "item": "",
    "status": ""
}

### First POST request
POST http://localhost:8000/api/todos/
Content-Type: application/json

{
    "item": "Nostrum iusto rerum.",
    "status": "56"
}

### First Todo PUT Request
POST http://localhost:8000/api/todos/2?_method=PUT
Content-Type: application/json

{
    "item": "Nostrum iusto rerum.",
    "status": "In Progress"
}

### Second Todo PUT Request
POST http://localhost:8000/api/todos/2?_method=PUT
Content-Type: application/json

{
    "item": "Nostrum iusto rerum.",
    "status": "Done"
}

### First DELETE Request
DELETE http://localhost:8000/api/todos/3